# Generated by Django 4.1.7 on 2023-07-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_banners',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
