# Generated by Django 4.1.7 on 2023-08-22 14:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_ticket_quantity_bought'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4c3ee9b2-50d9-42d2-bc82-bd1edd87c2f6'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.UUIDField(default=uuid.UUID('28790963-d685-496f-b987-eb7cca598d6f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dc6c54f6-437e-457f-9b25-e5899a4f770b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='venue',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6a499098-eb8d-48d9-8006-caa0b3826030'), editable=False, primary_key=True, serialize=False),
        ),
    ]
