# Generated by Django 4.1.7 on 2023-08-24 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_alter_event_id_alter_ticket_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_organiser',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
